// Generated by CoffeeScript 1.9.2
(function() {
  var Main, Wave, WaveComponent, __TIMER, getSign;

  WaveComponent = (function() {
    function WaveComponent() {
      this.y = 0;
      this.a = 0;
      this.v = 0;
      this.next = null;
      this.prev = null;
    }

    WaveComponent.prototype.connect = function(prev, next) {
      this.prev = prev;
      return this.next = next;
    };

    WaveComponent.prototype.update = function() {
      var friction, k_b, k_u;
      k_u = 1.0;
      k_b = 0.1;
      friction = 0.1;
      this.a = -this.y * k_u - this.v * friction;
      if (this.prev) {
        this.a -= (this.y - this.prev.y) * k_b;
      }
      if (this.next) {
        this.a -= (this.y - this.next.y) * k_b;
      }
      this.v += this.a;
      return this.y += this.v;
    };

    return WaveComponent;

  })();

  Wave = (function() {
    function Wave(canvas, ctx) {
      var i, wave_len;
      wave_len = 7;
      this.array = (function() {
        var j, ref, results;
        results = [];
        for (i = j = 0, ref = wave_len; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
          results.push(new WaveComponent);
        }
        return results;
      })();
      this.connectWaveComponents();
      this.gravity = {
        x: 12,
        y: 30
      };
      this.canvas = canvas;
      this.ctx = ctx;
    }

    Wave.prototype.connectWaveComponents = function() {
      var i, j, next, prev, ref, results;
      results = [];
      for (i = j = 0, ref = this.array.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        prev = next = null;
        if (i !== 0) {
          prev = this.array[i - 1];
        }
        if (i !== this.array.length - 1) {
          next = this.array[i + 1];
        }
        results.push(this.array[i].connect(prev, next));
      }
      return results;
    };

    Wave.prototype.update = function() {
      var c, j, len, ref, results;
      ref = this.array;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        c = ref[j];
        results.push(c.update());
      }
      return results;
    };

    Wave.prototype.draw = function() {
      var defalult_y, i, j, margin, ref, size, x, y;
      this.ctx.lineWidth = 2;
      this.ctx.strokeStyle = "#FF0000";
      this.ctx.fillStyle = "rgba(255, 0, 0, 0.5)";
      defalult_y = this.canvas.height * 0.4;
      size = Math.sqrt(Math.pow(this.canvas.width, 2) + Math.pow(this.canvas.height, 2));
      margin = (size - this.canvas.width) / 2;
      this.ctx.beginPath();
      this.ctx.save();
      this.ctx.translate(this.canvas.width / 2, this.canvas.height / 2);
      this.ctx.rotate(Math.atan2(-this.gravity.x, -this.gravity.y));
      this.ctx.translate(-this.canvas.width / 2, -this.canvas.height / 2);
      for (i = j = 0, ref = this.array.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        x = size / (this.array.length - 1) * i - margin;
        y = this.array[i].y + defalult_y;
        if (x === 0) {
          this.ctx.moveTo(x, y);
        } else {
          this.ctx.lineTo(x, y);
        }
      }
      this.ctx.lineTo(this.canvas.width + margin, this.canvas.height + margin);
      this.ctx.lineTo(-margin, this.canvas.height + margin);
      this.ctx.closePath();
      this.ctx.fill();
      return this.ctx.restore();
    };

    Wave.prototype.giveAccel = function(accel) {
      var a;
      a = 3;
      if (accel.x > 0) {
        return this.givePulse(0, a * accel.x);
      } else {
        return this.givePulse(-1, a * -accel.x);
      }
    };

    Wave.prototype.givePulse = function(i, v) {
      while (i < 0) {
        i += this.array.length;
      }
      return this.array[i].v = v;
    };

    return Wave;

  })();

  Main = (function() {
    function Main() {
      this.initCanvas();
      this.accel = {
        x: 0,
        y: 0,
        z: 0
      };
      this.gravity = {
        x: 0,
        y: -10,
        z: 0
      };
      this.wave = new Wave(this.canvas, this.ctx);
      this.counter = 0;
    }

    Main.prototype.initCanvas = function() {
      var c, ctx;
      c = document.getElementById("main_canvas");
      c.width = $(window).width();
      c.height = $(window).height();
      ctx = c.getContext("2d");
      this.canvas = c;
      return this.ctx = ctx;
    };

    Main.prototype.update = function() {
      this.wave.gravity = this.gravity;
      this.wave.giveAccel(this.accel);
      this.wave.update();
      return this.counter += 1;
    };

    Main.prototype.draw = function() {
      this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      return this.wave.draw();
    };

    Main.prototype.devicemotionHandler = function(event) {
      this.accel.x = event.acceleration.x;
      this.accel.y = event.acceleration.y;
      this.accel.z = event.acceleration.z;
      this.gravity.x = event.accelerationIncludingGravity.x - this.accel.x;
      this.gravity.y = event.accelerationIncludingGravity.y - this.accel.y;
      this.gravity.z = event.accelerationIncludingGravity.z - this.accel.z;
      return this.gravity.y -= Math.abs(this.gravity.z);
    };

    Main.prototype.drawAccel = function() {
      var ctx, h, max, w, x, y, z;
      ctx = this.ctx;
      x = this.accel.x;
      y = this.accel.y;
      z = this.accel.z;
      h = this.canvas.height;
      w = this.canvas.width;
      max = 10;
      ctx.lineWidth = 2;
      ctx.strokeStyle = "#FF0000";
      ctx.fillStyle = "#FF0000";
      ctx.beginPath();
      ctx.moveTo(w / 2, h / 2);
      ctx.lineTo(w / 2 + x / max * w / 2, h / 2 + y / max * h / 2);
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(w / 2 + x / max * w / 2, h / 2 + y / max * h / 2, 8, 0, 2 * Math.PI, false);
      return ctx.fill();
    };

    return Main;

  })();

  window.myevent = null;

  __TIMER = null;

  $(function() {
    var app;
    app = new Main;
    window.addEventListener("devicemotion", function(event) {
      return app.devicemotionHandler(event);
    });
    return __TIMER = setInterval(function() {
      app.update();
      return app.draw();
    }, 33);
  });

  getSign = function(n) {
    var num;
    if (n >= 0) {
      "+";
    } else {
      "-";
    }
    num = Math.floor(Math.abs(n) * 100) / 100;
    return num.toString();
  };

}).call(this);
